backend/config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  # mount Spree::Core::Engine, at: '/spree'
  
  # Main application routes
  scope '/api', module: 'api', defaults: {format: :json} do
    resources :taxonomies, only: :index
    get 'taxons/*permalink', to: 'taxons#show'
    resources :products, only: %i(index show)
    resource :cart do
      post :add_variant
      post :guest_login
      put :update_variant
      put :change_variant
      put :remove_adjustment
      delete :remove_variant
    end
    resource :account
    resources :passwords
    resources :credit_cards, only: :destroy
    resources :addresses, only: :destroy
    resources :countries, only: :index
    resources :orders, only: %i(index show)
    resource :corporate_accounts
  end

  mount Spree::Core::Engine, at: '/spree'

  Spree::Core::Engine.add_routes do
    namespace :admin do
      resources :order_info_options
      resources :coupons
      resources :products do
        resources :product_variant_types do
          collection do
            post :update_positions
          end
        end
        resources :product_variant_values 
      end
      resources :corporate_accounts
      resources :product_price_sets
      resources :product_prices
    end
  end

end

backend/app/models/spree/corporate_account.rb
class Spree::CorporateAccount < Spree::Base
    before_save :address_email_save
    
    validates :company_id, presence: true
    validates_uniqueness_of :company_id
    validates :company_name, presence: true
    validates :email, presence: true
    validates :country, presence: true
    validates :state, presence: true
    validates :zip_code, presence: true
    validates :contact_phone, presence: true
    validates :address1, presence: true
    validates :city, presence: true

    validates :password, length: {minimum: 6}
    validates :checkout_password, length: {minimum: 6}

    validates_confirmation_of :password
    validates_confirmation_of :checkout_password

    belongs_to :country, class_name: "Spree::Country"
    belongs_to :state, class_name: "Spree::State"

    # belongs_to :shipping_categories, class_name: "Spree::ShippingCateogry", :foreign_key => "shipping_category_id"
    belongs_to :product_price_set, class_name: "Spree::ProductPriceSet", :foreign_key => "product_price_set_id"

    has_many :users, class_name: "Spree::User"
    belongs_to :spree_billing_types, :foreign_key => "billing_type_id"

    def address_email_save
        self.email = email.downcase
        self.address = [self.address1, self.address2, self.city, self.state, self.country] * ','
    end

end

backend/app/controllers/api/corporate_accounts_controller.rb
module Api
    class CorporateAccountsController < BaseController
        skip_before_action :verify_authenticity_token

        def create
            @corporate_account = Spree::CorporateAccount.create(corporate_account_params)
            if @corporate_account.persisted?
                render_corp_account
            else
                invalid_resource!(@corporate_account)
            end
        end

        def show
            # @corporate_account = Spree::CorporateAccount.find(1)
            # render_corp_account
        end

        private
            def corporate_account_params
                params.require(:corporate_user).permit(:id,
                                                        :company_id,
                                                        :company_name,
                                                        :email,
                                                        :password,
                                                        :password_confirmation,
                                                        :checkout_password,
                                                        :checkout_password_confirmation,
                                                        :password,
                                                        :company,
                                                        :address1,
                                                        :address2,
                                                        :city,
                                                        :state_name,
                                                        :state_id,
                                                        :country_id,
                                                        :zip_code,
                                                        :contact_phone,
                                                        :address,
                                                        :shipping_category_id,
                                                        :product_price_set_id)
            end

            def render_corp_account
                render json: @corporate_account,
                    #    scope: @corporate_account,
                       root: true,
                       serializer: CorporateAccountSerializer
            end
    end
end

backend/app/controllers/spree/admin/corporate_accounts_controller.rb
module Spree
    module Admin
        class CorporateAccountsController < ResourceController
        end
    end
end

backend/app/helpers/api/corporate_accounts_helper.rb
module Api::CorporateAccountsHelper
end

backend/app/helpers/spree/admin/corporate_accounts_helper.rb
module Spree::Admin::CorporateAccountsHelper
end

backend/app/views/spree/admin/corporate_accounts/_form.html.erb
<% s_or_b = "ca" %>

<div data-hook="admin_corporate_account_form_fields" class="row">
    <div class="col-xs-12 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">
                <%= Spree.t(:general_settings) %>
                </h1>
            </div>
            <div class="panel-body">
                <div class="col-xs-12 col-md-12">
                    <%= f.field_container :company_id, class: ['form-group'] do %>
                        <%= f.label :company_id, Spree.t(:company_id) %><span class="required">(id)*</span>
                        <%= f.text_field :company_id, class: 'form-control' %>
                        <%= f.error_message_on :company_id %>
                    <% end %>
                </div>

                <div class="col-xs-12 col-md-12">
                    <%= f.field_container :company_name, class: ['form-group'] do %>
                        <%= f.label :company_name, Spree.t(:company_name) %><span class="required">*</span>
                        <%= f.text_field :company_name, class: 'form-control' %>
                        <%= f.error_message_on :company_name %>
                    <% end %>
                </div>

                <div class="col-xs-12 col-md-12">
                    <%= f.field_container :email, class: ['form-group'] do %>
                        <%= f.label :email, Spree.t(:email) %><span class="required">*</span>
                        <%= f.email_field :email, class: 'form-control' %>
                        <%= f.error_message_on :email %>
                    <% end %>
                </div>

                <div data-hook="admin_corporate_account_form_password_fields" class="col-xs-12 col-md-12">
                    <%= f.field_container :password, class: ['form-group'] do %>
                        <%= f.label :password, Spree.t(:password) %>
                        <%= f.password_field :password, class: 'form-control' %>
                        <%= f.error_message_on :password %>
                    <% end %>

                    <%= f.field_container :password_confirmation, class: ['form-group'] do %>
                        <%= f.label :password_confirmation, Spree.t(:confirm_password) %>
                        <%= f.password_field :password_confirmation, class: 'form-control' %>
                        <%= f.error_message_on :password_confirmation %>
                    <% end %>
                </div>
            
                <div data-hook="admin_corporate_account_form_checkout_password_fields" class="col-xs-12 col-md-12">
                    <%= f.field_container :checkout_password, class: ['form-group'] do %>
                        <%= f.label :checkout_password, Spree.t(:checkout_password) %>
                        <%= f.password_field :checkout_password, class: 'form-control' %>
                        <%= f.error_message_on :checkout_password %>
                    <% end %>

                    <%= f.field_container :checkout_password_confirmation, class: ['form-group'] do %>
                        <%= f.label :checkout_password_confirmation, Spree.t(:confirm_checkout_password) %>
                        <%= f.password_field :checkout_password_confirmation, class: 'form-control' %>
                        <%= f.error_message_on :checkout_password_confirmation %>
                    <% end %>
                </div> 

                <div data-hook="new_corporate_account_shipping_category" class="col-xs-12 col-md-12">
                    <%= f.field_container :shipping_category, class: ['form-group'] do %>
                    <%= f.label :shipping_category_id, Spree.t(:shipping_categories) %><span class="required">*</span>
                    <%= f.collection_select(:shipping_category_id, Spree::ShippingCategory.all, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', required: :required }) %>
                    <%= f.error_message_on :shipping_category_id %>
                    <% end %>
                </div>

                <div data-hook="accounts_product_price_set" class="col-xs-12 col-md-12">
                    <%= f.field_container :product_price_set, class: ['form-group'] do %>
                    <%= f.label :product_price_set_id, Spree.t(:product_price_set) %><span class="required">*</span>
                    <%= f.collection_select(:product_price_set_id, Spree::ProductPriceSet.all, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2', required: :required }) %>
                    <%= f.error_message_on :product_price_set_id %>
                    <% end %>
                </div>
            </div>
        </div>

    </div>
    <div class="col-xs-12 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title">
                <%= Spree.t(:company_address) %>
                </h1>
            </div>
            <div class="panel-body">
                <%= f.field_container :company, class: ["form-group"] do %>
                    <%= f.label :company, Spree.t(:company) %>
                    <%= f.text_field :company, class: 'form-control' %>
                    <%= f.error_message_on  :company %>
                <% end %>

                <%= f.field_container :address1, class: ["form-group"] do %>
                    <%= f.label :address1, Spree.t(:street_address) %><span class="required">*</span>
                    <%= f.text_field :address1, class: 'form-control' %>
                    <%= f.error_message_on :address1 %>
                <% end %>

                <%= f.field_container :address2, class: ["form-group"] do %>
                    <%= f.label :address2, Spree.t(:street_address_2) %>
                    <%= f.text_field :address2, class: 'form-control' %>
                    <%= f.error_message_on :address2 %>
                <% end %>

                <%= f.field_container :city, class: ["form-group"] do %>
                    <%= f.label :city, Spree.t(:city) %><span class="required">*</span>
                    <%= f.text_field :city, class: 'form-control' %>
                    <%= f.error_message_on :city %>
                <% end %>

                <%= f.field_container :zip_code, class: ["form-group"] do %>
                    <%= f.label :zip_code, Spree.t(:zip) %><span class="required">*</span>
                    <%= f.text_field :zip_code, class: 'form-control' %>
                    <%= f.error_message_on :zip_code %>
                <% end %>

                <div class="form-group">
                    <% @corporate_account.country ||= Spree::Country.first %>
                    <%= f.label :country_id, Spree.t(:country) %><span class="required">*</span>
                    <span id="<%= s_or_b %>country">                     
                        <%= f.collection_select :country_id, available_countries, :id, :name, {}, {class: 'select2'} %>
                    </span>
                </div>

                <%= f.field_container :state, class: ["form-group"] do %>
                    <%= f.label :state_id, Spree.t(:state) %><span class="required">*</span>
                    <span id="<%= s_or_b %>state">                     
                        <%= f.text_field :state_name, style: "display: #{@corporate_account.country.states.empty? ? 'block' : 'none'};",
                            disabled: !@corporate_account.country.states.empty?, class: 'form-control state_name' %>
                        <%= f.collection_select :state_id, @corporate_account.country.states.sort, :id, :name, { include_blank: true }, { class: 'select2', style: "display: #{@corporate_account.country.states.empty? ? 'none' : 'block' };", disabled: @corporate_account.country.states.empty? } %>
                    </span>
                <% end %>

                <%= f.field_container :contact_phone, class: ["form-group"] do %>
                    <%= f.label :contact_phone, Spree.t(:contact_phone) %><span class="required">*</span>
                    <%= f.text_field :contact_phone, class: 'form-control' %>
                    <%= f.error_message_on :contact_phone %>
                <% end %>

                <div class="form-group">
                    <%= f.label :billing_type_id, Spree.t(:billing_type) %><span class="required">*</span>
                    <%= f.collection_select :billing_type_id, Spree::BillingType.all, :id, :name, {}, {class: 'select2'} %>
                </div>

            </div>
        </div>
    </div>
</div>

<% content_for :head do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
      $('span#<%= s_or_b %>country .select2').on('change', function() { update_state('<%= s_or_b %>'); });
    });
  <% end %>
<% end %>

backend/app/views/spree/admin/corporate_accounts/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:corporate_accounts), spree.admin_corporate_accounts_url %> /
  <%= @corporate_account.email %>
<% end %>

<div data-hook="admin_corporate_account_edit_general_settings" class="panel panel-default">

  <div class="panel-body">
    <div data-hook="admin_corporate_account_edit_form_header">
      <%= render partial: 'spree/admin/shared/error_messages', locals: { target: @corporate_account } %>
    </div>

    <div data-hook="admin_corporate_account_edit_form">
      <%= form_for [:admin, @corporate_account], as: :corporate_account, url: spree.admin_corporate_account_url(@corporate_account), method: :put do |f| %>
        <%= render partial: 'form', locals: { f: f } %>

        <div data-hook="admin_corporate_account_edit_form_button">
          <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: spree.admin_corporate_accounts_url } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

backend/app/views/spree/admin/corporate_accounts/index.html.erb
<%= render partial: 'spree/admin/shared/corp_sidebar', locals: { current: :account } %>

<% content_for :page_title do %>
    <%= Spree.t(:corporate_accounts) %>
<% end %>

<% content_for :page_actions do %>
    <span id="new_ca_link">
      <%= button_link_to  Spree.t(:new_account), new_object_url, {class: "btn-success", icon: 'add', id: 'new_corporate_account_link'} %>
    </span>
<% end if can?(:create, Spree::CorporateAccount) %>


<% if @corporate_accounts.any? %>
  <table class="table" id="listing_corporate_accounts" data-hook>
    <thead>
      <tr data-hook="admin_corporate_accounts_index_headers">
        <th><%= Spree.t(:email) %></th>
        <th><%= Spree.t(:company_name) %></th>
        <th><%= Spree.t(:address) %></th>
        <th><%= Spree.t(:price_set) %></th>
        <th><%= Spree.t(:shipping) %></th>
        <th><%= Spree.t(:published) %></th>
        <th data-hook="admin_corporate_accounts_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @corporate_accounts.each do |corporate_account| %>
        <tr id="<%= spree_dom_id corporate_account %>" data-hook="admin_corporate_accounts_index_rows">
          <td class='corporate_account_email'><%=link_to corporate_account.email, edit_admin_corporate_account_url(corporate_account) %></td>
          <td class='corporate_account_name'><%= corporate_account.company_name %></td>
          <td class='corporate_account_address'><%= corporate_account.address %></td>
          <td class='corporate_account_price_set'><%= Spree::ProductPriceSet.find(corporate_account.product_price_set_id).name %></td>
          <td class='corporate_account_shipping'><%= Spree::ShippingCategory.find(corporate_account.shipping_category_id).name %></td>
          <td class='corporate_account_shipping'><%= Spree::BillingType.find(corporate_account.billing_type_id).name %></td>
          <td data-hook="admin_corporate_accounts_index_row_actions" class="actions actions-2 text-right">
            <%= link_to_edit corporate_account, no_text: true if can?(:edit, corporate_account) %>
            <%= link_to_delete corporate_account, no_text: true if can?(:delete, corporate_account) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::CorporateAccount)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

backend/app/views/spree/admin/corporate_accounts/new.html.erb
<% content_for :page_title do %>
    <%= link_to Spree.t(:corporate_accounts), spree.admin_corporate_accounts_url %> /
    <%= Spree.t(:new_corporate_account) %>
<% end %>

<div data-hook="admin_corporate_account_new_form_header">
    <%= render partial: "spree/admin/shared/error_messages", locals: { target: @corporate_account } %>
</div>

<div data-hook="admin_new_corporate_account_new_form">
    <%= form_for [:admin, @corporate_account], url: spree.admin_corporate_accounts_url, method: :post do |f| %>
        <%= render partial: "form", locals: {f: f} %>

        <div data-hook="admin_corporate_account_new_form_buttons">
            <%= render partial: "spree/admin/shared/new_resource_links" %>
        </div>
    <% end %>
</div>