backend/config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  # mount Spree::Core::Engine, at: '/spree'
  
  # Main application routes
  scope '/api', module: 'api', defaults: {format: :json} do
    resources :taxonomies, only: :index
    get 'taxons/*permalink', to: 'taxons#show'
    resources :products, only: %i(index show)
    resource :cart do
      post :add_variant
      post :guest_login
      put :update_variant
      put :change_variant
      put :remove_adjustment
      delete :remove_variant
    end
    resource :account
    resources :passwords
    resources :credit_cards, only: :destroy
    resources :addresses, only: :destroy
    resources :countries, only: :index
    resources :orders, only: %i(index show)
    resource :corporate_accounts
  end

  mount Spree::Core::Engine, at: '/spree'

  Spree::Core::Engine.add_routes do
    namespace :admin do
      resources :order_info_options
      resources :coupons
      resources :products do
        resources :product_variant_types do
          collection do
            post :update_positions
          end
        end
        resources :product_variant_values 
      end
      resources :corporate_accounts
      resources :product_price_sets
      resources :product_prices
    end
  end

end

backend/app/models/spree/order_info_option.rb
# class Spree::OrderInfoOption < Spree::Base
#     acts_as_list

#     with_options dependent: :destroy, inverse_of: :option_type do
#       has_many :option_values, -> { order(:position) }
#       has_many :product_option_types
#     end

#     has_many :products, through: :product_option_types

#     has_many :option_type_prototypes, class_name: 'Spree::OptionTypePrototype'
#     has_many :prototypes, through: :option_type_prototypes, class_name: 'Spree::Prototype'

#     with_options presence: true do
#       validates :name, uniqueness: { case_sensitive: false, allow_blank: true }
#       validates :presentation
#     end

#     default_scope { order(:position) }

#     accepts_nested_attributes_for :option_values, reject_if: lambda { |ov| ov[:name].blank? || ov[:presentation].blank? }, allow_destroy: true

#     after_touch :touch_all_products

#     private

#     def touch_all_products
#       products.update_all(updated_at: Time.current)
#     end
# end

backend/app/controllers/spree/admin/order_info_options_controller.rb
class Spree::Admin::OrderInfoOptionsController < Spree::Admin::ResourceController
    before_action :setup_new_option_value, only: :edit

    def update_values_positions
        ApplicationRecord.transaction do
            params[:positions].each do |id, index|
            Spree::OptionValue.where(id: id).update_all(position: index)
            end
        end

        respond_to do |format|
            format.html { redirect_to admin_product_variants_url(params[:product_id]) }
            format.js { render plain: 'Ok' }
        end
    end

    protected

    def location_after_save
        if @order_info_option.created_at == @order_info_option.updated_at
            edit_admin_option_type_url(@order_info_option)
        else
            admin_order_info_option_url
        end
    end

    private
    def setup_new_option_value
        # @order_info_option.option_values.build if @order_info_option.option_values.empty?
    end
end

backend/app/helpers/spree/admin/order_info_options_helper.rb
module Spree::Admin::OrderInfoOptionsHelper
end

backend/app/views/spree/admin/order_info_options/_form.html.erb
<div data-hook="admin_order_info_option_form" class="row">
  <div class="col-xs-12 col-md-4">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
  <div class="col-xs-12 col-md-4">
    <%= f.field_container :presentation, class: ['form-group'] do %>
      <%= f.label :presentation, Spree.t(:presentation) %> <span class="required">*</span>
      <%= f.text_field :presentation, class: 'form-control' %>
      <%= f.error_message_on :presentation %>
    <% end %>
  </div>
  <div class="col-xs-12 col-md-4">
    <%= f.field_container :description, class: ['form-group'] do %>
      <%= f.label :description, Spree.t(:description) %>
      <%= f.text_field :description, class: 'form-control' %>
    <% end %>
  </div>
</div>

backend/app/views/spree/admin/order_info_options/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:order_info_options), admin_order_info_options_url %> /
  <%= @order_info_option.name %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @property } %>

<%= form_for [:admin, @order_info_option] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

backend/app/views/spree/admin/order_info_options/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:order_info_options) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_order_info_option), new_object_url, { class: "btn-success", icon: 'add', id: 'admin_new_order_info_option' } %>
<% end if can?(:create, Spree::OrderInfoOption) %>

<table class="table" id="listing_products">
  <thead>
    <tr data-hook="admin_products_index_headers">
        <th colspan="2"><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:presentation) %></th>   
        <th><%= Spree.t(:description) %></th>
        <th data-hook="admin_order_info_options_index_header_actions" class="actions"></th>
      </tr>
  </thead>
  <tbody>
    <% @order_info_options.each do |order_info_option| %>
      <tr id="<%= spree_dom_id order_info_option %>" data-hook="admin_order_info_options_index_rows" class="<%= cycle('odd', 'even') %>">
        <td colspan="2"><%= order_info_option.name %></td>
        <td><%= order_info_option.presentation %></td>
        <td><%= order_info_option.description %></td>

        <td class="actions actions-3 text-right" data-hook="admin_order_info_options_index_row_actions">
          <%= link_to_edit order_info_option, no_text: true, class: 'edit' if can?(:edit, order_info_option) %>
          <%= link_to_delete order_info_option, no_text: true if can?(:delete, order_info_option) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

backend/app/views/spree/admin/order_info_options/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @order_info_option } %>

<% content_for :page_title do %>
  <%= link_to Spree.t(:order_info_options), admin_order_info_options_url %> /
  <%= Spree.t(:new_order_info_option) %>
<% end %>

<%= form_for [:admin, @order_info_option] do |f| %>
  <fieldset data-hook="new_order_info_option">
    <%= render partial: 'form', locals: { f: f } %>
    <div class="form-actions">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
  </fieldset>
<% end %>