backend/config/routes.rb
Rails.application.routes.draw do

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  # mount Spree::Core::Engine, at: '/spree'
  
  # Main application routes
  scope '/api', module: 'api', defaults: {format: :json} do
    resources :taxonomies, only: :index
    get 'taxons/*permalink', to: 'taxons#show'
    resources :products, only: %i(index show)
    resource :cart do
      post :add_variant
      post :guest_login
      put :update_variant
      put :change_variant
      put :remove_adjustment
      delete :remove_variant
    end
    resource :account
    resources :passwords
    resources :credit_cards, only: :destroy
    resources :addresses, only: :destroy
    resources :countries, only: :index
    resources :orders, only: %i(index show)
    resource :corporate_accounts
  end

  mount Spree::Core::Engine, at: '/spree'

  Spree::Core::Engine.add_routes do
    namespace :admin do
      resources :order_info_options
      resources :coupons
      resources :products do
        resources :product_variant_types do
          collection do
            post :update_positions
          end
        end
        resources :product_variant_values 
      end
      resources :corporate_accounts
      resources :product_price_sets
      resources :product_prices
    end
  end

end

backend/app/models/spree/product_price_set.rb
class Spree::ProductPriceSet < ActiveRecord::Base
    has_many :product_prices, class_name: "Spree::ProductPrice", :dependent => :destroy
    has_many :corporate_accounts, class_name: "Spree::CorporateAccount"
    has_many :products, class_name: "Spree::Product", through: :product_prices

    has_many :users, class_name: "Spree::User"
    
    accepts_nested_attributes_for :product_prices
end

backend/app/controllers/spree/admin/product_price_sets_controller.rb
module Spree
    module Admin
        class ProductPriceSetsController < ResourceController
            before_action :setup_new_product_price, only: :edit

            def setup_new_product_price
                @product_price_set.product_prices.build if @product_price_set.product_prices.empty?
            end

            private 
                def product_price_set_params
                    params.require(:product_price_set).permit(:name, product_prices_attributes: [:id, :price, :product_id])
                end
        end
    end
end

backend/app/helpers/spree/admin/product_price_sets_helper.rb
module Spree::Admin::ProductPriceSetsHelper
end

backend/app/views/spree/admin/product_price_sets/_form.html.erb
<div data-hook="admin_product_price_set_form_fields">
  <div data-hook="name" class="form-group">
    <%= f.field_container :name, class: ["form-group"] do %>
      <%= f.label :name, Spree.t(:name) %><br>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
</div>

backend/app/views/spree/admin/product_price_sets/_product_price_fields.html.erb
<tr class="product_price fields" id="spree_<%= dom_id(f.object) %>" data-hook="product_price">

  <td class="price_product">
      <%= f.collection_select :product_id, Spree::Product.all, :id, :name, {include_blank: true}, {class: 'select2'} %>
  </td>
  <td class="price"><%= f.text_field :price, class: "form-control" %></td>
  <td class="actions actions-1 text-center"><%= link_to_icon_remove_fields f %></td>
</tr>

backend/app/views/spree/admin/product_price_sets/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:product_price_sets), spree.admin_product_price_sets_url %> /
  <%= @product_price_set.name %>
<% end %>

<% content_for :page_actions do %>
  <span id="new_add_product_price" data-hook>
    <%= button_link_to Spree.t(:add_product_price), "javascript:;", { icon: 'add', :'data-target' => "tbody#product_prices", class: 'btn-success spree_price_add_fields' } %>
  </span>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product_price_set } %>

<%= form_for [:admin, @product_price_set] do |f| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= Spree.t(:product_prices) %>
      </h1>
    </div>
    <div class="panel-body">
      <%= render partial: 'form', locals: { f: f } %>
    </div>
    <table class="table table-condensed table-bordered" data-hook >
      <thead data-hook="product_price_header">
        <tr>
          <th colspan="1"><%= Spree.t(:product) %> <span class="required">*</span></th>
          <th><%= Spree.t(:price) %> <span class="required">*</span></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="product_prices">
        <% if @product_price_set.product_prices.empty? %>
          <tr id="none" data-hook="product_price_none">
            <td colspan="2"><%= Spree.t(:none) %></td>
            <td class="actions text-center"></td>
          </tr>
        <% else %>
          <%= f.fields_for :product_prices do |product_price_form| %>
            <%= render partial: 'product_price_fields', locals: { f: product_price_form } %>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="panel-footer text-center">
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    </div>
  </div>
<% end %>

<% content_for :head do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
        var uniqueId = 1;
        console.log(uniqueId);
        $('.spree_price_add_fields').click(function() {
          var target = $(this).data("target");

          var $table_row = $(target + ' tr:visible:last');
          $table_row.find('.select2').select2('destroy');
          var new_table_row = $table_row.clone();

          var new_id = new Date().getTime() + (uniqueId++);

          new_table_row.find("input, select").each(function () {
            var el = $(this);
            if (el.context.tagName == "SELECT"){
              el.select2();
              el.val("0").trigger('change');
            }
            else
              el.val("");
            el.prop("id", el.prop("id").replace(/\d+/, new_id))
            el.prop("name", el.prop("name").replace(/\d+/, new_id))
          })
          
          $table_row.find('.select2').select2();

          new_table_row.find("a").each(function () {
            var el = $(this);
            el.prop('href', '#');  
          })
          $(target).prepend(new_table_row);
        })
    });
  <% end %>
<% end %>

backend/app/views/spree/admin/product_price_sets/index.html.erb
<%= render partial: 'spree/admin/shared/corp_sidebar', locals: { current: :price } %>

<% content_for :page_title do %>
    <%= Spree.t(:product_price_set) %>
<% end %>

<% content_for :page_actions do %>
    <span id="new_ps_link">
      <%= button_link_to  Spree.t(:new_price_set), new_object_url, {class: "btn-success", icon: 'add', id: 'new_product_price_set_link'} %>
    </span>
<% end if can?(:create, Spree::ProductPriceSet) %>


<% if @product_price_sets.any? %>
  <table class="table" id="listing_product_price_sets" data-hook>
    <thead>
      <tr data-hook="admin_product_price_sets_index_headers">
        <th><%= Spree.t(:name) %></th>
        <th data-hook="admin_product_price_sets_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @product_price_sets.each do |product_price_set| %>
        <tr id="<%= spree_dom_id product_price_set %>" data-hook="admin_product_price_sets_index_rows">
          <td class='product_price_set_name'><%=link_to product_price_set.name, edit_admin_product_price_set_url(product_price_set) %></td>
                    
          <td data-hook="admin_product_price_sets_index_row_actions" class="actions actions-2 text-right">
            <%= link_to_edit product_price_set, no_text: true if can?(:edit, product_price_set) %>
            <%= link_to_delete product_price_set, no_text: true if can?(:delete, product_price_set) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ProductPriceSet)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>

backend/app/views/spree/admin/product_price_sets/new.html.erb
<% content_for :page_title do %>
    <%= link_to Spree.t(:product_price_sets), spree.admin_product_price_sets_url %> /
    <%= Spree.t(:new_price_set) %>
<% end %>

<%= render partial: "spree/admin/shared/error_messages", locals: { target: @product_price_set } %>

<%= form_for [:admin, @product_price_set] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>